import platform
#['c', 'm', 'e', 'a', 's', 'o', 'v', 'k', 'y', 'u', 'z', 'q', 'p', 'h', 't', 'r', 'd', 'g', 'b', 'l', 'w', 'i', 'j', 'n', 'x', 'f']
print(platform.machine())
print(platform.processor())
print(platform.system())
print(platform.node())
printableList = [platform.machine(),platform.processor(),platform.system(),platform.node()]
print(printableList)
for item in printableList:
    itemIndex = printableList.index(item)
    item.replace('A','replacedC')
    item.replace('B','replacedM')
    item.replace('C','replacedE')
    item.replace('D','replacedA')
    item.replace('E','replacedS')
    item.replace('F','replacedO')
    item.replace('G','replacedV')
    item.replace('H','replacedK')
    item.replace('I','replacedY')
    item.replace('J','replacedU')
    item.replace('K','replacedZ')
    item.replace('L','replacedQ')
    item.replace('M','replacedP')
    item.replace('N','replacedH')
    item.replace('O','replacedT')
    item.replace('P','replacedR')
    item.replace('Q','replacedD')
    item.replace('R','replacedG')
    item.replace('S','replacedB')
    item.replace('T','replacedL')
    item.replace('U','replacedW')
    item.replace('V','replacedI')
    item.replace('W','replacedJ')
    item.replace('X','replacedN')
    item.replace('Y','replacedX')
    item.replace('Z','replacedF')
    item.replace('a','replacedc')
    item.replace('b','replacedm')
    item.replace('c','replacede')
    item.replace('d','replaceda')
    item.replace('e','replaceds')
    item.replace('f','replacedo')
    item.replace('g','replacedv')
    item.replace('h','replacedk')
    item.replace('i','replacedy')
    item.replace('j','replacedu')
    item.replace('k','replacedz')
    item.replace('l','replacedq')
    item.replace('m','replacedp')
    item.replace('n','replacedh')
    item.replace('o','replacedt')
    item.replace('p','replacedr')
    item.replace('q','replacedd')
    item.replace('r','replacedg')
    item.replace('s','replacedb')
    item.replace('t','replacedl')
    item.replace('u','replacedw')
    item.replace('v','replacedi')
    item.replace('w','replacedj')
    item.replace('x','replacedn')
    item.replace('y','replacedx')
    item.replace('z','replacedf')
    print(str(itemIndex)+item)
    printableList[itemIndex] = item
print(printableList)
systemInfo = ((platform.machine()),(platform.processor()),(platform.system()),(platform.node()))
print(systemInfo)